### ISSUE TITLE
ArgumentError on interpolated string

### ISSUE THREAD

**Issue by jsmestad** [100phlecs/tailwind_formatter#18]
On a billing page I have the following code:

```heex
<.img src={~p"/images/#{"card-#{@card.brand}.svg"}"} />
```

The formatter errors with the following:

```
mix format failed for file: lib/heads_down_web/live/subscription_live/edit.html.heex
** (ArgumentError) Invalid inlined elixir function:
 "card-#{@card.brand -- missing interpolation terminator: "}" (for string starting at line 1)
    lib/tailwind_formatter.ex:61: anonymous fn/1 in TailwindFormatter.validate_inline_fns/1
    (elixir 1.14.3) lib/enum.ex:975: Enum."-each/2-lists^foreach/1-0-"/2
    lib/tailwind_formatter.ex:58: TailwindFormatter.validate_inline_fns/1
    lib/tailwind_formatter.ex:19: TailwindFormatter.format/2
    (mix 1.14.3) lib/mix/tasks/format.ex:576: Mix.Tasks.Format.format_file/2
    (elixir 1.14.3) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.3) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 4.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

---

Thank you so much for this library!

**Comment by 100phlecs** [comment]
Thanks for the report!

Didn't consider nested interpolation. 
Now using negative lookahead within the Regex to account for nesting.
I'll be making a release soon, but if you could try the latest commit on your repo and see if any other issues crop up I would appreciate it.

You'll want to put:
```elixir
      {:tailwind_formatter, github: "100phlecs/tailwind_formatter", override: true},
```

in your mix deps.

 Let me know if you run into any other issues. The more test cases the better :-)
